spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: ${db_url:jdbc:mysql://127.0.0.1:3306/ebike?characterEncoding=utf8&useSSL=false}
    username: ${db_username:root}
    password: ${db_password:root}
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
