server:
  port: ${server_port:8082}
  servlet:
    context-path: ${context_path:/shop-app}
spring:
  jmx:
    enabled: false
  servlet:
      multipart:
        max-file-size: 10MB
        max-request-size: 30MB
  datasource:
    type: org.apache.commons.dbcp2.BasicDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: ${db_url:jdbc:mysql://127.0.0.1:3306/ebike?characterEncoding=utf8&useSSL=false}
    username: ${db_username:root}
    password: ${db_password:root}
    dbcp2:
      initial-size: 1
      max-total: 500
      max-idle: 2
      min-idle: 2
      max-wait-millis: 5000
      time-between-eviction-runs-millis: 3000
      min-evictable-idle-time-millis: 30000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
  data:
     redis:
        database: 0
        host: ${redis_host:localhost}
        port: ${redis_port:6379}
        password: ${redis_password:}
        timeout: 0
        pool:
          max-idle: 8
          min-idle: 0
          max-active: 8
          max-wait: -1

  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: none
#      naming:
#        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true



